# https://github.com/TypoCI/spellcheck-action
name: Typo CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spellcheck:
    name: Typo CI (GitHub Action)
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-spellcheck]')"
    steps:
    - name: TypoCheck
      uses: typoci/spellcheck-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}